// doc/src/components/react/Example.tsx
import "monza-editor/style.css";
import { Editor } from "@monza-editor/react";
import type { JSX } from "react";
import { highlight } from "../../utility.js";
import styles from "./Example.module.css";

export const Example = (): JSX.Element => (
  <Editor
    className={styles.main}
    onHighlight={highlight}
    value='console.log("Hello, React!");'
  />
);

// doc/src/components/solid/Example.tsx
/* @jsxImportSource solid-js */

import "monza-editor/style.css";
import { Editor } from "@monza-editor/solid";
import type { JSX } from "solid-js";
import { highlight } from "../../utility.js";
import styles from "./Example.module.css";

export const Example = (): JSX.Element => (
  <Editor
    class={styles.main}
    onHighlight={highlight}
    value='console.log("Hello, Solid.js!");'
  />
);
